export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Home } from './Home'
export { default as Details } from './Details'
export { default as Favorites } from './Favorites'
export { default as EventForm } from './EventForm'
