export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as Home } from './Home'
export { default as Details } from './Details'
export { default as Favorites } from './Favorites'
